dist: xenial
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: 
  - python3 -m unittests.test_backend
  - python3 -m unittests.test_database
